### ISSUE TITLE
Migration 81 drop incident_expire_timestamp in pokestop table.

### ISSUE THREAD

**Issue by pamoyrdm** [versx/RDMopole2#58]
Migration 81 for RDM 

ALTER TABLE pokestop
DROP COLUMN pokestop_display,
DROP COLUMN incident_expire_timestamp,
DROP COLUMN grunt_type;

sqlMessage: "Unknown column 'grunt_type' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: '\n' +
    '    SELECT \n' +
    '        lat, \n' +
    '        lon,\n' +
    '        name,\n' +
    '        grunt_type,\n' +
    '        incident_expire_timestamp,\n' +
    '        updated\n' +
    '    FROM\n' +
    '        pokestop\n' +
    '    WHERE\n' +
    '        incident_expire_timestamp > UNIX_TIMESTAMP()\n' +
    '        AND enabled = 1;\n' +

**Comment by versx** [comment]
Closing this since https://github.com/versx/RDMopole2/pull/52 fixes this issue. Make sure to add `"hasMultipleInvasions": true` under your `db.scanner` config section.
